### ISSUE TITLE
пофикси ты уже 

### ISSUE THREAD

**Issue by LifeHacker125132** [Kiriyaga7615/karasic#3]
ку, ты же знаешь что кулрендер плохо отображается на табличках заборчиках и тд 
ты или сделай его нормальным или сделай так что бы он не рендерился на них

**Comment by Kiriyaga7615** [comment]
ффффвыыфвфывфывыфвыфсыфвсыфвсфывсфывысв

**Comment by EurekaEffect** [comment]
та как же похуй
